version: '3.7'
services:
    wbapp:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: 'wbapp'
    wbdb:
        image: mysql:5.7
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: "wb"
            MYSQL_ROOT_PASSWORD: "admin"
            MYSQL_USER: "wbuser"
            MYSQL_PASSWORD: "admin"
        volumes:
            - wb-mysql:/var/lib/mysql
volumes:
    wb-mysql:
